apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kourier.yaml

images:
  - name: gcr.io/knative-releases/knative.dev/net-kourier/cmd/kourier
    newName: imroc/knative-net-kourier
    newTag: latest