apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- eventing-core.yaml
images:
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  newName: imroc/knative-eventing-controller
  newTag: latest
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  newName: imroc/knative-eventing-webhook
  newTag: latest
