apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- net-istio.yaml
images:
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newName: imroc/knative-net-istio-controller
  newTag: latest
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newName: imroc/knative-net-istio-webhook
  newTag: latest
